spring:
  application:
    name: ms-loan
  datasource:
#    platform: postgres
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5432/library_db}
    username: postgres
    password: Holabb54
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  port: 9000
  
key: ABCDabcd1234

